
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package first_page;

import static ankh.morpork.AnkhMorpork.usedStack;
import static first_page.Symbols.as;
import static first_page.Symbols.selectedArea;
import static first_page.first_page.active_turn;
import static first_page.first_page.gb;
import static first_page.first_page.playerObj;
import static first_page.gameBoard.bt;
import static first_page.gameBoard.sc;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;


/**
 *
 * @author n_bhaga
 */
public class beginTurn extends javax.swing.JFrame {

    /**
     * Creates new form beginTurn
     */
    public beginTurn() {
        initComponents();
    }

    
    public  JLabel[] lb = new JLabel[10];
    public JRadioButton[] rb = new JRadioButton[10];
    public JPanel jp = new JPanel();
    ButtonGroup radioGroup = new ButtonGroup();
    public JButton jb;
    public static Symbols sym = new Symbols();
static ArrayList<Integer> al;
static int one = 1;
static int total_symbols = 0;
static String selectedCard;



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playerLabel = new javax.swing.JLabel();
        hcLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        personalityLabel = new javax.swing.JLabel();
        cashLabel = new javax.swing.JLabel();
        minionsLabel = new javax.swing.JLabel();
        buildingsLabel = new javax.swing.JLabel();
        areasLabel = new javax.swing.JLabel();
        cardsLabel = new javax.swing.JLabel();
        playCardButton = new javax.swing.JButton();
        pCard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setText("Current Player:");

        playerLabel.setText("jLabel2");

        hcLabel.setText("jLabel2");

        colorLabel.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hcLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(playerLabel)
                    .addComponent(hcLabel)
                    .addComponent(colorLabel))
                .addGap(29, 29, 29))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setText("Personality:");

        jLabel3.setText("Cash:");

        jLabel4.setText("Minions:");

        jLabel5.setText("Buildings:");

        jLabel6.setText("Areas:");

        jLabel7.setText("Cards In Hands:");

        personalityLabel.setText("jLabel8");
        personalityLabel.setMaximumSize(new java.awt.Dimension(50, 50));
        personalityLabel.setMinimumSize(new java.awt.Dimension(50, 50));

        cashLabel.setText("jLabel9");

        minionsLabel.setText("jLabel10");

        buildingsLabel.setText("jLabel11");

        areasLabel.setText("jLabel12");

        cardsLabel.setText("jLabel13");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashLabel)
                    .addComponent(minionsLabel)
                    .addComponent(buildingsLabel)
                    .addComponent(personalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cardsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addComponent(areasLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(personalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cashLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(minionsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(buildingsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(areasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cardsLabel))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        playCardButton.setText("Play Card");
        playCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playCardButtonActionPerformed(evt);
            }
        });

        pCard.setText("Show Personality Card");
        pCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 674, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(pCard)
                .addGap(29, 29, 29)
                .addComponent(playCardButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCard)
                    .addComponent(playCardButton))
                .addContainerGap(378, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCardActionPerformed

final ImageIcon icon1 = new javax.swing.ImageIcon(getClass().getResource("\\Personality\\"+ playerObj[active_turn].Personality+ ".png"));
JOptionPane.showMessageDialog(null, "", "Personality Card",
   JOptionPane.INFORMATION_MESSAGE,   icon1);        

// TODO add your handling code here:
    }//GEN-LAST:event_pCardActionPerformed

    private void playCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playCardButtonActionPerformed
    
            System.out.println("check1");
            al=new ArrayList<Integer>();
            bt.setVisible(false);
            sc = new selectedCard();
            sc.setLayout(new FlowLayout()); 
            sc.setVisible(true);
            sc.jp = new JPanel();
            sc.lb = new JLabel[10];
            sc.cb = new JCheckBox[10];
            sc.playerLabel.setText("Player " + (first_page.active_turn+one));
            sc.colorLabel.setText(playerObj[first_page.active_turn].Color);
            sc.colorLabel.setForeground(Color.getColor(playerObj[first_page.active_turn].Color));
            if(playerObj[first_page.active_turn].isHuman)
                sc.ishumanLabel.setText("H"); 
            else
                sc.ishumanLabel.setText("C");
            
            // get the name of the selected card
            for (Enumeration<AbstractButton> buttons = bt.radioGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

                if (button.isSelected()) {
                    selectedCard = button.getName();
                }                                                     
            }
                    
            System.out.println("selected card:" + selectedCard);
            for (cardDetails s : cardDetails.values())
            {
                if (selectedCard.equals(s.toString()))
                {
                    for(int i=0;i<s.action.length;i++)
                    {
                        System.out.printf("selected card name: %s\n" ,s.getName());
                        al.add(s.getAction(i));
                        System.out.printf("selected card actions: %d\n",al.get(i));
                    }
                }
            }
            
            // getting number of symbols for selected card
            for(int i=0;i<al.size();i++){
                if(al.get(i) != null)
                {
                    System.out.println("no for symbol:" + al.get(i));
                    total_symbols++;    // total number of symbols for current selected card
                }
            }

            // display symbols for selected card
            for(int i=0;i<al.size();i++){
               
                URL iconURL = getClass().getResource("\\symbols\\" + al.get(i) + ".png" );
                ImageIcon icon = new ImageIcon(iconURL);

                sc.cb[i] = new JCheckBox();
                
                System.out.println("nehal bhagat:" + sym.getSymbols(al.get(i)));
                sc.cb[i].setName(sym.getSymbols(al.get(i)));
                sc.jp.add(sc.cb[i]);
                sc.cb[0].setSelected(true);

                if(al.get(i) == 5)
                {sc.cb[i].setSelected(true);
                }   
                sc.lb[i] = new JLabel();
                sc.lb[i].setIcon(icon);
                sc.jp.add(sc.lb[i]);
               // sc.add(sc.jp); 
            }
            
                URL iconURL = getClass().getResource("\\player cards\\" + selectedCard + ".png" );
                ImageIcon icon = new ImageIcon(iconURL);
           
                sc.label = new JLabel();
                
             
            sc.label.setIcon(icon);
            sc.jp.add(sc.label);
            sc.add(sc.jp);
            System.out.println("check2");  
            first_page.playerObj[active_turn].CardsInHand.remove(selectedCard);
            usedStack.push(selectedCard);
            System.out.println("cards in hand:" + first_page.playerObj[active_turn].CardsInHand);
            System.out.println("used cards:" + usedStack);
             if("gr29".equals(selectedCard))
             { 
                 JOptionPane.showMessageDialog(sc, "This card is not having any symbol\n Please end your turn ", "Message", JOptionPane.WARNING_MESSAGE );
                 sc.setVisible(false);
                 gb.endTurnButton.setEnabled(true);
             } 


// TODO add your handling code here:
    }//GEN-LAST:event_playCardButtonActionPerformed

     
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beginTurn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beginTurn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beginTurn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beginTurn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beginTurn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel areasLabel;
    public javax.swing.JLabel buildingsLabel;
    public javax.swing.JLabel cardsLabel;
    public javax.swing.JLabel cashLabel;
    public javax.swing.JLabel colorLabel;
    public javax.swing.JLabel hcLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JLabel minionsLabel;
    public javax.swing.JButton pCard;
    public javax.swing.JLabel personalityLabel;
    public javax.swing.JButton playCardButton;
    public javax.swing.JLabel playerLabel;
    // End of variables declaration//GEN-END:variables
}
